<a href="https://colab.research.google.com/github/sejalapeno/movie-recommender-system/blob/main/movierecommend_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [110]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [111]:
movies = pd.read_csv('/content/drive/MyDrive/GColab_Mount/tmdb_5000_movies.csv')
credits = pd.read_csv('/content/drive/MyDrive/GColab_Mount/tmdb_5000_credits.csv')
print("datasets loaded")

datasets loaded

In [112]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [113]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [114]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [115]:
movies.shape

(4803, 20)

In [116]:
movies=movies.merge(credits,on='title')

In [117]:
movies.shape

(4809, 23)

In [118]:
movies.head()
# genres
## id (but movie id taken)
# keywords
# overview
## popularity
# title
## vote avg
# movie id
# cast
# crew(only director)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [119]:
# genres
# keywords
# overview
# title
# movie id
# cast
# crew(only director)
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [120]:
#movies.isnull().sum() 3 overviews are empty
movies.dropna(inplace=True)
movies.shape

<ipython-input-120-37b814b6bf85>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.dropna(inplace=True)

(4806, 7)

In [121]:
import ast

In [122]:
#function will return a list by taking names from the respective field from the dictionary that acts like an object in the list of dictionaries.
def convert(text):
    L=[]
    for i in ast.literal_eval(text):
        L.append(i['name'])

    return L

In [123]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [124]:
movies['keywords'] = movies['keywords'].apply(convert)

In [125]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [126]:
def convert_3(text):
    L=[]
    counter=0
    for i in ast.literal_eval(text):
        if counter< 3:
            L.append(i['name'])
            counter+=1

    return L

In [127]:
movies['cast'] = movies['cast'].apply(convert_3)

In [128]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [129]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [130]:
def fetch_director(text):
    L=[]
    for i in ast.literal_eval(text):
        if(i['job']=='Director'):
            L.append(i['name'])

    return L

In [131]:
movies['crew'] = movies['crew'].apply(fetch_director)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [132]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [133]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [134]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [135]:
movies['overview'] = movies['overview'].apply(lambda x:x.split()) #converts overview text to list
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [136]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [137]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [138]:
new_df = movies.drop(columns=['overview','genres','keywords','cast','crew'])
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [139]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x)) #list to string
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [140]:
new_df['tags'][3999]

'A ghost hunter uses bottles to capture troublesome spirits. RohitJugraj'

# Vectorization

In [141]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [142]:
vector = cv.fit_transform(new_df['tags']).toarray()

In [143]:
vector.shape

(4806, 5000)

In [144]:
from sklearn.metrics.pairwise import cosine_similarity

In [145]:
similarity = cosine_similarity(vector)  #finding the cosine distance between vectors

In [146]:
type(similarity)

numpy.ndarray

In [147]:
similarity[789]

array([0.       , 0.       , 0.       , ..., 0.0860663, 0.       ,
       0.       ])

In [148]:
new_df[new_df['title'] == 'Batman']
#new_df[new_df['title'] == 'Batman'].index[0]

      movie_id   title                                               tags
1362       268  Batman  The Dark Knight of Gotham City begins his war ...
1363      2661  Batman  The Dark Knight of Gotham City begins his war ...
1364       268  Batman  The Dynamic Duo faces four super-villains who ...
1365      2661  Batman  The Dynamic Duo faces four super-villains who ...

# Recommend function

In [149]:
# Here we need to make sure that reverse is True and the tuple is sorted acc to index[1] i.e. the actual distance.
#enumerate similarity converts ndarray into a tuple with index
sorted(list(enumerate(similarity[11])),reverse=True, key=lambda x: x[1])

[(11, 1.0),
 (2, 0.373878250552983),
 (1346, 0.3335505593800666),
 (3340, 0.2935682819759931),
 (1749, 0.2746175181905448),
 (29, 0.269069117598525),
 (4077, 0.2687419249432849),
 (1134, 0.26311740579210874),
 (4343, 0.2569280097268784),
 (277, 0.25016291953504993),
 (147, 0.23788041338002103),
 (1537, 0.2300789234172203),
 (3255, 0.2250703454761599),
 (3166, 0.2229978693352242),
 (170, 0.21790681682020446),
 (1719, 0.21653278478430665),
 (3355, 0.21059925059706258),
 (1103, 0.20846909961254162),
 (695, 0.19611613513818407),
 (808, 0.19418390934515434),
 (568, 0.19223226273338134),
 (134, 0.1921537845661046),
 (3347, 0.18681617943926832),
 (1592, 0.17948717948717946),
 (1648, 0.17722938923964168),
 (1670, 0.17471413945365305),
 (2194, 0.17471413945365305),
 (4304, 0.1727334068350122),
 (972, 0.17255919256291524),
 (3363, 0.17118419700436519),
 (3147, 0.1710334403066895),
 (2680, 0.167093470609201),
 (308, 0.16694514082354445),
 (2919, 0.16694514082354445),
 (3310, 0.16477051091432687),
 (973, 0.16239958858823),
 (218, 0.16012815380508713),
 (4010, 0.16012815380508713),
 (4641, 0.16012815380508713),
 (596, 0.1601281538050871),
 (1087, 0.1601281538050871),
 (1864, 0.1601281538050871),
 (711, 0.15701857325533194),
 (58, 0.15695698526580623),
 (3622, 0.15585730003983933),
 (1464, 0.15534712747612348),
 (3595, 0.15191090506255),
 (3720, 0.15191090506255),
 (1425, 0.1513068831672006),
 (1203, 0.15114173098063566),
 (3077, 0.15097027121927944),
 (3721, 0.15097027121927944),
 (1903, 0.14867525836251316),
 (164, 0.14867525836251314),
 (1079, 0.14867525836251314),
 (1274, 0.14867525836251314),
 (2589, 0.14867525836251314),
 (3890, 0.14867525836251314),
 (127, 0.146943671674129),
 (1936, 0.14651588715165131),
 (683, 0.1465158871516513),
 (700, 0.14617633655117152),
 (1004, 0.14617633655117152),
 (3322, 0.14617633655117152),
 (1276, 0.14484136487558028),
 (2466, 0.14484136487558028),
 (3511, 0.1437993271357627),
 (139, 0.14351616441832768),
 (1672, 0.14322297480788657),
 (3863, 0.14322297480788657),
 (99, 0.14153462926807447),
 (366, 0.14153462926807445),
 (1616, 0.14153462926807445),
 (939, 0.14121975762272054),
 (1154, 0.13977131156292244),
 (1681, 0.13977131156292244),
 (3664, 0.13937366833451514),
 (123, 0.1386750490563073),
 (495, 0.13655774839978377),
 (1400, 0.13655774839978377),
 (1403, 0.13655774839978377),
 (1886, 0.13655774839978377),
 (1195, 0.13533299049019168),
 (3320, 0.13533299049019168),
 (425, 0.1345345587992625),
 (893, 0.13397282541141672),
 (408, 0.13355611265883557),
 (1085, 0.13355611265883557),
 (3211, 0.13355611265883557),
 (3297, 0.13355611265883557),
 (370, 0.13344012817090595),
 (987, 0.13344012817090595),
 (3978, 0.13323467750529824),
 (4261, 0.13323467750529824),
 (4502, 0.13323467750529824),
 (1677, 0.1319717610643751),
 (2404, 0.1319717610643751),
 (1843, 0.1307440900921227),
 (2823, 0.12988108336653278),
 (1879, 0.1283881477532739),
 (3733, 0.1283881477532739),
 (1248, 0.1282051282051282),
 (1367, 0.1282051282051282),
 (2008, 0.1282051282051282),
 (290, 0.12810252304406972),
 (1631, 0.12810252304406972),
 (2741, 0.12810252304406972),
 (969, 0.12725695259515554),
 (334, 0.12659242088545833),
 (372, 0.12659242088545833),
 (1733, 0.12659242088545833),
 (2080, 0.12659242088545833),
 (2377, 0.12659242088545833),
 (219, 0.12561485860426555),
 (1076, 0.12561485860426555),
 (1589, 0.12561485860426555),
 (4196, 0.12561485860426555),
 (1634, 0.12532010295690074),
 (213, 0.12403473458920845),
 (3731, 0.12403473458920845),
 (1041, 0.12403473458920844),
 (1437, 0.12403473458920844),
 (76, 0.1235415527768502),
 (724, 0.1235415527768502),
 (23, 0.12326671027227314),
 (1492, 0.12326671027227314),
 (149, 0.12301385521570944),
 (153, 0.12301385521570944),
 (1534, 0.12301385521570944),
 (1898, 0.12301385521570944),
 (758, 0.12209657262637608),
 (856, 0.12209657262637608),
 (1202, 0.12209657262637608),
 (794, 0.12104550653376048),
 (1027, 0.12104550653376048),
 (1431, 0.12104550653376048),
 (1440, 0.12104550653376048),
 (2235, 0.12104550653376048),
 (140, 0.1207011373963169),
 (2650, 0.1207011373963169),
 (2713, 0.1207011373963169),
 (208, 0.12009611535381534),
 (866, 0.12009611535381534),
 (1621, 0.12009611535381534),
 (3303, 0.12009611535381534),
 (3496, 0.12009611535381534),
 (3528, 0.12009611535381534),
 (4783, 0.12009611535381534),
 (398, 0.11935247900657214),
 (767, 0.11935247900657214),
 (392, 0.11894020669001051),
 (840, 0.11894020669001051),
 (1523, 0.11894020669001051),
 (4673, 0.11894020669001051),
 (1938, 0.11804804116247142),
 (2056, 0.1180480411624714),
 (227, 0.11694106924093722),
 (369, 0.11694106924093722),
 (402, 0.11694106924093722),
 (151, 0.11651034560709261),
 (205, 0.11651034560709261),
 (1323, 0.11651034560709261),
 (2297, 0.11651034560709261),
 (2882, 0.11651034560709261),
 (4231, 0.11651034560709261),
 (4460, 0.11651034560709261),
 (1106, 0.1165103456070926),
 (307, 0.1156117059711339),
 (88, 0.11503946170861017),
 (245, 0.11503946170861017),
 (512, 0.11503946170861017),
 (3301, 0.11503946170861017),
 (2333, 0.11437725271791938),
 (3044, 0.11437725271791938),
 (1476, 0.11322770341445959),
 (2390, 0.11322770341445959),
 (2394, 0.11322770341445959),
 (3832, 0.11322770341445959),
 (4412, 0.11322770341445959),
 (830, 0.11322770341445956),
 (1237, 0.11322770341445956),
 (3552, 0.11322770341445956),
 (3647, 0.11322770341445956),
 (2153, 0.11211213233271874),
 (345, 0.11211213233271873),
 (1322, 0.11211213233271873),
 (741, 0.11149893466761211),
 (1866, 0.11149893466761211),
 (2204, 0.11149893466761211),
 (3236, 0.11149893466761211),
 (3428, 0.11149893466761211),
 (739, 0.11020775375559674),
 (1005, 0.11020775375559674),
 (1624, 0.11020775375559674),
 (1727, 0.11020775375559674),
 (2323, 0.11020775375559674),
 (3413, 0.11020775375559674),
 (3627, 0.11020775375559674),
 (3972, 0.11020775375559674),
 (3982, 0.11020775375559674),
 (2963, 0.10997646755364592),
 (126, 0.10984700727621793),
 (508, 0.10984700727621793),
 (2211, 0.10984700727621793),
 (2243, 0.10984700727621793),
 (354, 0.10895340841010223),
 (2256, 0.10895340841010223),
 (500, 0.10826639239215334),
 (548, 0.10826639239215334),
 (1161, 0.10826639239215334),
 (1380, 0.10826639239215334),
 (2013, 0.10826639239215334),
 (2128, 0.10826639239215334),
 (3805, 0.10826639239215334),
 (1836, 0.10809494906623499),
 (252, 0.10795837927188262),
 (179, 0.10741723110591492),
 (490, 0.10741723110591492),
 (613, 0.10741723110591492),
 (1090, 0.10741723110591492),
 (1721, 0.10741723110591492),
 (2117, 0.10741723110591492),
 (2808, 0.10741723110591492),
 (3875, 0.10741723110591492),
 (4351, 0.10741723110591492),
 (188, 0.10699012312772824),
 (187, 0.10675210253672475),
 (929, 0.10675210253672475),
 (1006, 0.10675210253672475),
 (2352, 0.10675210253672475),
 (2418, 0.10675210253672475),
 (4240, 0.10675210253672475),
 (1282, 0.10604746049596295),
 (1080, 0.10529962529853128),
 (1511, 0.10529962529853128),
 (1961, 0.10529962529853128),
 (2072, 0.10529962529853128),
 (4374, 0.10529962529853128),
 (773, 0.10482848367219183),
 (1044, 0.10482848367219183),
 (1194, 0.10482848367219183),
 (1723, 0.10482848367219183),
 (2342, 0.10482848367219183),
 (2925, 0.10482848367219183),
 (2980, 0.10482848367219183),
 (3055, 0.10482848367219183),
 (3336, 0.10482848367219183),
 (403, 0.10423454980627081),
 (210, 0.10390486669322622),
 (312, 0.10390486669322622),
 (350, 0.10390486669322622),
 (731, 0.10390486669322622),
 (1061, 0.10390486669322622),
 (2820, 0.10390486669322622),
 (3152, 0.10390486669322622),
 (2049, 0.10300524052492097),
 (1297, 0.10256410256410256),
 (2527, 0.10256410256410256),
 (4401, 0.10256410256410256),
 (61, 0.10241831129983783),
 (498, 0.10241831129983783),
 (826, 0.10241831129983783),
 (1049, 0.10241831129983783),
 (1291, 0.10241831129983783),
 (1410, 0.10241831129983783),
 (1666, 0.10241831129983783),
 (2564, 0.10241831129983783),
 (2584, 0.10241831129983783),
 (2937, 0.10241831129983783),
 (3839, 0.10241831129983783),
 (3886, 0.10241831129983783),
 (3999, 0.10241831129983783),
 (4270, 0.10241831129983783),
 (4479, 0.10241831129983783),
 (304, 0.10241831129983782),
 (17, 0.10168147934776052),
 (1109, 0.10127393670836667),
 (1783, 0.10127393670836667),
 (1900, 0.10127393670836667),
 (2007, 0.10127393670836667),
 (3080, 0.10127393670836667),
 (3229, 0.10127393670836667),
 (3614, 0.10127393670836667),
 (4352, 0.10127393670836665),
 (33, 0.10016708449412667),
 (237, 0.10016708449412667),
 (263, 0.10016708449412667),
 (487, 0.10016708449412667),
 (590, 0.10016708449412667),
 (1055, 0.10016708449412667),
 (1327, 0.10016708449412667),
 (1423, 0.10016708449412667),
 (1494, 0.10016708449412667),
 (2067, 0.10016708449412667),
 (2228, 0.10016708449412667),
 (3621, 0.10016708449412667),
 (4357, 0.10016708449412667),
 (804, 0.10003126465607107),
 (1086, 0.10003126465607107),
 (2014, 0.10003126465607107),
 (2395, 0.10003126465607107),
 (4268, 0.10003126465607107),
 (4383, 0.10003126465607107),
 (4425, 0.10003126465607107),
 (2539, 0.09930726528736966),
 (4330, 0.09930726528736966),
 (2052, 0.09883324222148016),
 (2354, 0.09883324222148016),
 (2549, 0.09855206599818042),
 (400, 0.09805806756909202),
 (660, 0.09805806756909202),
 (781, 0.09805806756909202),
 (1513, 0.09805806756909202),
 (2090, 0.09805806756909202),
 (2579, 0.09805806756909202),
 (2622, 0.09805806756909202),
 (2645, 0.09805806756909202),
 (3421, 0.09805806756909202),
 (3490, 0.09805806756909202),
 (4490, 0.09805806756909202),
 (444, 0.09767725810110087),
 (446, 0.09767725810110087),
 (870, 0.09767725810110087),
 (2241, 0.09767725810110087),
 (3184, 0.09767725810110087),
 (3458, 0.09767725810110087),
 (985, 0.09705231721239391),
 (158, 0.09656090991705352),
 (412, 0.09656090991705352),
 (782, 0.09656090991705352),
 (1075, 0.09656090991705352),
 (1272, 0.09656090991705352),
 (1281, 0.09656090991705352),
 (3025, 0.09656090991705352),
 (4071, 0.09656090991705352),
 (4710, 0.09656090991705352),
 (186, 0.09638582199437336),
 (389, 0.09607689228305229),
 (604, 0.09607689228305229),
 (691, 0.09607689228305229),
 (920, 0.09607689228305229),
 (1158, 0.09607689228305229),
 (7, 0.09548198320525772),
 (580, 0.09548198320525772),
 (831, 0.09548198320525772),
 (1285, 0.09548198320525772),
 (1748, 0.09548198320525772),
 (2752, 0.09548198320525772),
 (3407, 0.09548198320525772),
 (4603, 0.09548198320525772),
 (665, 0.09443843292997713),
 (1798, 0.09443843292997713),
 (2209, 0.09443843292997713),
 (4105, 0.09443843292997713),
 (433, 0.09421114395319916),
 (825, 0.09421114395319916),
 (876, 0.09421114395319916),
 (976, 0.09421114395319916),
 (1047, 0.09421114395319916),
 (1658, 0.09421114395319916),
 (1756, 0.09421114395319916),
 (2281, 0.09421114395319916),
 (2283, 0.09421114395319916),
 (2378, 0.09421114395319916),
 (2615, 0.09421114395319916),
 (2652, 0.09421114395319916),
 (2981, 0.09421114395319916),
 (3356, 0.09421114395319916),
 (3376, 0.09421114395319916),
 (3692, 0.09421114395319916),
 (3857, 0.09421114395319916),
 (2596, 0.09342836717341035),
 (83, 0.09342836717341034),
 (119, 0.09245003270420486),
 (442, 0.09245003270420486),
 (574, 0.09245003270420486),
 (981, 0.09245003270420486),
 (1117, 0.09245003270420486),
 (1444, 0.09245003270420486),
 (1962, 0.09245003270420486),
 (3505, 0.09245003270420486),
 (4395, 0.09245003270420486),
 (4405, 0.09245003270420486),
 (4697, 0.09245003270420486),
 (581, 0.09245003270420485),
 (762, 0.09245003270420485),
 (941, 0.09245003270420485),
 (1052, 0.09245003270420485),
 (1054, 0.09245003270420485),
 (1275, 0.09245003270420485),
 (2348, 0.09245003270420485),
 (3277, 0.09245003270420485),
 (3435, 0.09245003270420485),
 (3778, 0.09245003270420485),
 (1256, 0.0916057224828689),
 (108, 0.0915018021743355),
 (600, 0.0915018021743355),
 (1191, 0.0915018021743355),
 (3740, 0.0915018021743355),
 (122, 0.09078412990032037),
 (259, 0.09078412990032037),
 (511, 0.09078412990032037),
 (922, 0.09078412990032037),
 (931, 0.09078412990032037),
 (1181, 0.09078412990032037),
 (1306, 0.09078412990032037),
 (2206, 0.09078412990032037),
 (2795, 0.09078412990032037),
 (2814, 0.09078412990032037),
 (3238, 0.09078412990032037),
 (3353, 0.09078412990032037),
 (4148, 0.09078412990032037),
 (4426, 0.09078412990032037),
 (4505, 0.09078412990032037),
 (4781, 0.09078412990032037),
 (152, 0.09078412990032035),
 (180, 0.09058216273156766),
 (351, 0.09058216273156766),
 (3330, 0.09058216273156766),
 (13, 0.08968970586617499),
 (698, 0.08968970586617499),
 (2162, 0.08968970586617499),
 (28, 0.08920515501750789),
 (242, 0.08920515501750789),
 (244, 0.08920515501750789),
 (306, 0.08920515501750789),
 (960, 0.08920515501750789),
 (1149, 0.08920515501750789),
 (1443, 0.08920515501750789),
 (1453, 0.08920515501750789),
 (1809, 0.08920515501750789),
 (2552, 0.08920515501750789),
 (2817, 0.08920515501750789),
 (3263, 0.08920515501750789),
 (3264, 0.08920515501750789),
 (3948, 0.08896008544727063),
 (314, 0.0888231183368655),
 (873, 0.0888231183368655),
 (1315, 0.0888231183368655),
 (1673, 0.0888231183368655),
 (2213, 0.0888231183368655),
 (2274, 0.0888231183368655),
 (2388, 0.0888231183368655),
 (2480, 0.0888231183368655),
 (2541, 0.0888231183368655),
 (2675, 0.0888231183368655),
 (2999, 0.0888231183368655),
 (3607, 0.0888231183368655),
 (3728, 0.0888231183368655),
 (3988, 0.0888231183368655),
 (4348, 0.0888231183368655),
 (673, 0.08798117404291673),
 (1030, 0.08798117404291673),
 (1650, 0.08798117404291673),
 (72, 0.08770580193070292),
 (282, 0.08770580193070292),
 (333, 0.08770580193070292),
 (356, 0.08770580193070292),
 (405, 0.08770580193070292),
 (844, 0.08770580193070292),
 (1253, 0.08770580193070292),
 (2824, 0.08770580193070292),
 (3365, 0.08770580193070292),
 (3403, 0.08770580193070292),
 (4164, 0.08770580193070292),
 (1305, 0.08716272672808179),
 (3000, 0.08716272672808179),
 (45, 0.0863667034175061),
 (1462, 0.0863667034175061),
 (1992, 0.0863667034175061),
 (2498, 0.0863667034175061),
 (2603, 0.0863667034175061),
 (4656, 0.0863667034175061),
 (121, 0.08627959628145762),
 (468, 0.08627959628145762),
 (544, 0.08627959628145762),
 (1196, 0.08627959628145762),
 (1485, 0.08627959628145762),
 (1746, 0.08627959628145762),
 (2169, 0.08627959628145762),
 (2261, 0.08627959628145762),
 (2858, 0.08627959628145762),
 (774, 0.08559209850218259),
 (3510, 0.08559209850218259),
 (3578, 0.08559209850218259),
 (3854, 0.08559209850218259),
 (3914, 0.08559209850218259),
 (4647, 0.08559209850218259),
 (4736, 0.08559209850218259),
 (4737, 0.08559209850218259),
 (96, 0.08492077756084468),
 (166, 0.08492077756084468),
 (761, 0.08492077756084468),
 (859, 0.08492077756084468),
 (1142, 0.08492077756084468),
 (1269, 0.08492077756084468),
 (1430, 0.08492077756084468),
 (1490, 0.08492077756084468),
 (1859, 0.08492077756084468),
 (2251, 0.08492077756084468),
 (4569, 0.08492077756084468),
 (3608, 0.08483796839677037),
 (4034, 0.08439494725697222),
 (3522, 0.084103426706236),
 (46, 0.08362420100070908),
 (86, 0.08362420100070908),
 (104, 0.08362420100070908),
 (203, 0.08362420100070908),
 (513, 0.08362420100070908),
 (753, 0.08362420100070908),
 (786, 0.08362420100070908),
 (2202, 0.08362420100070908),
 (2662, 0.08362420100070908),
 (2879, 0.08362420100070908),
 (3024, 0.08362420100070908),
 (4048, 0.08338763984501665),
 (1139, 0.0826898230594723),
 (1349, 0.0826898230594723),
 (2061, 0.0826898230594723),
 (2250, 0.0826898230594723),
 (2332, 0.0826898230594723),
 (3128, 0.0826898230594723),
 (3218, 0.0826898230594723),
 (3441, 0.0826898230594723),
 (52, 0.08238525545716345),
 (283, 0.08238525545716345),
 (449, 0.08238525545716345),
 (539, 0.08238525545716345),
 (576, 0.08238525545716345),
 (644, 0.08238525545716345),
 (965, 0.08238525545716345),
 (996, 0.08238525545716345),
 (1548, 0.08238525545716345),
 (1651, 0.08238525545716345),
 (2066, 0.08238525545716345),
 (2160, 0.08238525545716345),
 (2224, 0.08238525545716345),
 (2686, 0.08238525545716345),
 (2901, 0.08238525545716345),
 (3140, 0.08238525545716345),
 (3646, 0.08238525545716345),
 (47, 0.08200923681047297),
 (1509, 0.08200923681047297),
 (80, 0.0817150563075767),
 (1641, 0.08134518347820842),
 (1659, 0.08134518347820842),
 (1741, 0.08134518347820842),
 (0, 0.081199794294115),
 (207, 0.081199794294115),
 (332, 0.081199794294115),
 (603, 0.081199794294115),
 (900, 0.081199794294115),
 (1046, 0.081199794294115),
 (1913, 0.081199794294115),
 (2063, 0.081199794294115),
 (2433, 0.081199794294115),
 (3037, 0.081199794294115),
 (3078, 0.0806970043558403),
 (131, 0.08006407690254357),
 (291, 0.08006407690254357),
 (330, 0.08006407690254357),
 (335, 0.08006407690254357),
 (472, 0.08006407690254357),
 (534, 0.08006407690254357),
 (540, 0.08006407690254357),
 (680, 0.08006407690254357),
 (714, 0.08006407690254357),
 (858, 0.08006407690254357),
 (1033, 0.08006407690254357),
 (1270, 0.08006407690254357),
 (1360, 0.08006407690254357),
 (1401, 0.08006407690254357),
 (1943, 0.08006407690254357),
 (2780, 0.08006407690254357),
 (3142, 0.08006407690254357),
 (3527, 0.08006407690254357),
 (3747, 0.08006407690254357),
 (3752, 0.08006407690254357),
 (4044, 0.08006407690254357),
 (4131, 0.08006407690254357),
 (4142, 0.08006407690254357),
 (4238, 0.08006407690254357),
 (65, 0.07944581222989573),
 (150, 0.07944581222989573),
 (190, 0.07944581222989573),
 (755, 0.07944581222989573),
 (322, 0.07897471897389846),
 (503, 0.07897471897389846),
 (594, 0.07897471897389846),
 (632, 0.07897471897389846),
 (1602, 0.07897471897389846),
 (1764, 0.07897471897389846),
 (1921, 0.07897471897389846),
 (2683, 0.07897471897389846),
 (3638, 0.07897471897389846),
 (4098, 0.07897471897389846),
 (1136, 0.07888947910127371),
 (3203, 0.07884165279854434),
 (138, 0.07792865001991967),
 (295, 0.07792865001991967),
 (988, 0.07792865001991967),
 (1015, 0.07792865001991967),
 (1273, 0.07792865001991967),
 (1454, 0.07792865001991967),
 (1519, 0.07792865001991967),
 (2755, 0.07792865001991967),
 (3090, 0.07792865001991967),
 (3102, 0.07792865001991967),
 (62, 0.07767356373806174),
 (653, 0.07767356373806174),
 (850, 0.07767356373806174),
 (1078, 0.07767356373806174),
 (1197, 0.07767356373806174),
 (1613, 0.07767356373806174),
 (1779, 0.07767356373806174),
 (1939, 0.07767356373806174),
 (2275, 0.07767356373806174),
 (2326, 0.07767356373806174),
 (2510, 0.07767356373806174),
 (2558, 0.07767356373806174),
 (3155, 0.07767356373806174),
 (3253, 0.07767356373806174),
 (3288, 0.07767356373806174),
 (3420, 0.07767356373806174),
 (3513, 0.07767356373806174),
 (3918, 0.07767356373806174),
 (4248, 0.07767356373806174),
 (4568, 0.07767356373806174),
 (1143, 0.07710865759549869),
 (70, 0.07692307692307693),
 (595, 0.07692307692307693),
 (659, 0.07692307692307693),
 (958, 0.07692307692307693),
 (1009, 0.07692307692307693),
 (1204, 0.07692307692307693),
 (1561, 0.07692307692307693),
 (1920, 0.07692307692307693),
 (2009, 0.07692307692307693),
 (2143, 0.07692307692307693),
 (2201, 0.07692307692307693),
 (2592, 0.07692307692307693),
 (2709, 0.07692307692307693),
 (3401, 0.07692307692307693),
 (4230, 0.07692307692307693),
 (424, 0.07655590023509527),
 (950, 0.07655590023509527),
 (168, 0.075955452531275),
 (204, 0.075955452531275),
 (300, 0.075955452531275),
 (587, 0.075955452531275),
 (643, 0.075955452531275),
 (990, 0.075955452531275),
 (1185, 0.075955452531275),
 (1383, 0.075955452531275),
 (1451, 0.075955452531275),
 (1470, 0.075955452531275),
 (2408, 0.075955452531275),
 (3307, 0.075955452531275),
 (3433, 0.075955452531275),
 (3675, 0.075955452531275),
 (125, 0.0756534415836003),
 (800, 0.07548513560963972),
 (1288, 0.07548513560963972),
 (1385, 0.07548513560963972),
 (1521, 0.07548513560963972),
 (1773, 0.07548513560963972),
 (2259, 0.07548513560963972),
 (2551, 0.07548513560963972),
 (2772, 0.07548513560963972),
 (2935, 0.07548513560963972),
 (2961, 0.07548513560963972),
 (3730, 0.07548513560963972),
 (4130, 0.07548513560963972),
 (4463, 0.07548513560963972),
 (4557, 0.07548513560963972),
 (129, 0.07502344849205331),
 (271, 0.07502344849205331),
 (510, 0.07502344849205331),
 (723, 0.07502344849205331),
 (732, 0.07502344849205331),

In [150]:
def recommend(search_title):
    index = new_df[new_df['title'] == search_title].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True, key=lambda x: x[1])
    for i in distances[1:11]:
        print(new_df.iloc[i[0]].title)
        #print(i)

In [151]:
recommend('Prisoners')

(4231, 0.28005601680560194)
(3363, 0.25717224993681986)
(4736, 0.25717224993681986)
(538, 0.25197631533948484)
(3511, 0.24195539543709926)
(1476, 0.22680460581325726)
(4412, 0.22680460581325726)
(4142, 0.22452510468485445)
(1519, 0.21853668936906195)
(3238, 0.2182178902359924)

In [152]:
import pickle

In [153]:
pickle.dump(new_df.to_dict(),open('movie_list_dict.pkl','wb')) # opening new_df in write binary mode and saving in movie_list.pkl format
# pickle.dump(similarity,open('similarity.pkl','wb'))
print("success")

success

In [154]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)